### ISSUE TITLE
Test API's for testing role based permissions 

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#1]
To finish authorization services we need 3 more API endpoints
- [x] That is restricted to users with role 1,
- [x] That is restricted to users with role 2,
- [x] That is restricted to users with ether role 1 or 2

**Comment by johnnymagic** [comment]
This is now ready.  Let me know if I can change anything.  As we figure out our workflow, we may have these test methods a lot.  If we do, I'll organize under the appropriate controller so there isn't one big Test controller.

How To:
http://screencast.com/t/fjm6Q0cvqhXk

Swagger is up:  http://doddlenowapi-test.us-west-2.elasticbeanstalk.com/swagger/ui/index#/

**Comment by badluck13** [comment]
@johnnymagic great as always, @iborismb check this out.
