### ISSUE TITLE
Add paging to candidate routes

### ISSUE THREAD

**Issue by johnnymagic** [DoddleNow/DoddleNow-BackEnd#14]
{{url}}/api/v1/HA/5d85285d-401b-4b12-8692-db70e81df0b3/jobs/0a18a498-442a-4705-b525-0cc99e0a4f8e/candidates/

[10:49]  
and

[10:49]  
{{url}}/api/v1/HA/5d85285d-401b-4b12-8692-db70e81df0b3/candidates

[10:50]  
on both of them, standard feature set, paging, orderby and sort

[10:51]  
plus filters:favorited or coffeeConnected (edited)

[10:51]  
Globals:
totalCandidates,
totalFavorited,
totalCoffeeConnected

**Comment by badluck13** [comment]
Add this info for each candidate:
SCL Matching % - can be random for now
yearsOfExperience - we have that data point under preferences.experience on get profile call.

**Comment by badluck13** [comment]
Hey @johnnymagic can you check if filter is implemented, I always get same data, no matter what filter is:

`{{url}}/api/v1/HA/5d85285d-401b-4b12-8692-db70e81df0b3/candidates?page=1&perPage=5&orderby=lastName&sort=ASC&filter=favorited`

And here is return with 2 candidates, even when `"totalFavorited": 0` 
```
{
  "totalCount": 2,
  "totalPages": 1,
  "currentPage": 1,
  "totalCandidates": 2,
  "totalFavorited": 0,
  "totalCoffeeConnected": 2,
  "data": [
    {
      "userId": "d0fbb274-f20d-4611-a7a0-6a7ea99dfa2b",
      "firstName": "Mary",
      "lastName": "Treble",
      "eMail": "maryTreble3@mailinator.com",
      "applicantApplied": false,
      "clientInterest": false,
      "clientStarred": false,
      "coffeeConnect": true,
      "exclude": false,
      "location": "Los Angeles, CA",
      "locationDistance": 0,
      "candidateGuid": "bf08efe8-b001-44e1-8fb1-4be97cafa47d",
      "candidateAlias": "HPBF08E",
      "sclMatch": 86,
      "yearsOfExperienceStr": "10+ Years"
    },
    {
     "userId": "d0fbb274-f20d-4611-a7a0-6a7ea99dfa2b",
      "firstName": "Mary",
      "lastName": "Treble",
      "eMail": "maryTreble3@mailinator.com",
      "applicantApplied": true,
      "clientInterest": true,
      "clientStarred": false,
      "coffeeConnect": true,
      "exclude": false,
      "location": "Los Angeles, CA",
      "locationDistance": 0,
      "candidateGuid": "909a86a7-b636-41c4-aa65-88e4a5238657",
      "candidateAlias": "HP909A8",
      "sclMatch": 93,
      "yearsOfExperienceStr": "10+ Years"
    }
  ]
}
```

**Comment by johnnymagic** [comment]
Yes, I wasn't sure if it needed filters.  I added "favorited" and "coffeeconnected" as filters to look for.  Let me know if you need others.
