### ISSUE TITLE
HA Missing data on GET candidate

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#16]
Need to update GET {{url}}/api/v1/HA/clientId/jobs/jobId/candidates/candidateId to match needed data on the viewport

Here is how full connected profile of candidate looks:

![ha-view-hp-profile-connected](https://cloud.githubusercontent.com/assets/186824/21006024/6f7ab33a-bd37-11e6-9ade-c7676c61a609.jpg)

We need access to all this data, currently we got only workhistory, and some basic data about candidate

**Comment by johnnymagic** [comment]
Hi Bojan.  I did this but implemented a solution I'm not certain will work for you.  The output is different if a candidate is coffeeConnect.  Take a look at this and let me know if it works for you.

http://screencast.com/t/xvZmPyrGgDm

**Comment by badluck13** [comment]
Hi @johnnymagic It works for me great when the candidate is coffee connected. But we also need to show some data for HA to decide to coffee connect. For me only difference that coffee connected and not accounts should have is contact data, name, email, address, phone, etc. Then I can play with them as much as I want. 

I like how you did it with the same call depending on the flag connected, I just would want to get more for the first screen. We need to sell them to be connected. Maybe to get last item from Work history and Education in to the base call?
