### ISSUE TITLE
API: Applicant count on Get Job is not correct

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#17]
Steps to reproduce:

- Get HA token
- Go to Get job {{url}}/api/v1/HA/5d85285d-401b-4b12-8692-db70e81df0b3/jobs/0a18a498-442a-4705-b525-0cc99e0a4f8e
here is the code it returns: 
```
{
  "id": "0a18a498-442a-4705-b525-0cc99e0a4f8e",
  "name": "Truck Driver Enhanced",
  "description": "Drive truck 9-9",
  "clientName": "Kaiser Permanente",
  "clientDescription": null,
  "clientAddress": null,
  "clientAddress2": null,
  "clientCity": null,
  "clientState": null,
  "clientZip": null,
  "specialities": null,
  "starred": null,
  "clientInterested": false,
  "clientId": "5d85285d-401b-4b12-8692-db70e81df0b3",
  "startDate": "2016-11-22",
  "endDate": "2016-12-28",
  "applied": null,
  "sclMatch": 0,
  "shifts": [
    "Day",
    "Night"
  ],
  "newApplicants": 1,
  "applicantCount": 0,
  "active": true,
  "sclMatchPreference": 0
}
```
- See that applicantCount is 0, and that newApplicants is 1,
- Go to Get Client Job Candidates {{url}}/api/v1/HA/5d85285d-401b-4b12-8692-db70e81df0b3/jobs/0a18a498-442a-4705-b525-0cc99e0a4f8e/candidates?page=1&perPage=5&orderby=lastName&sort=ASC
- See that there is one Candidate
```
{
  "totalCount": 1,
  "totalPages": 1,
  "currentPage": 1,
  "totalCandidates": 1,
  "totalFavorited": 0,
  "totalCoffeeConnected": 0,
  "data": [
    {
      "userId": "d0fbb274-f20d-4611-a7a0-6a7ea99dfa2b",
      "firstName": "Mary",
      "lastName": "Treble",
      "eMail": "maryTreble3@mailinator.com",
      "applicantApplied": false,
      "clientInterest": true,
      "clientStarred": false,
      "coffeeConnect": false,
      "exclude": false,
      "location": "Los Angeles, CA",
      "locationDistance": 0,
      "candidateGuid": "909a86a7-b636-41c4-aa65-88e4a5238657",
      "candidateAlias": "HP909A8",
      "sclMatch": 10,
      "yearsOfExperienceStr": "10+ Years"
    }
  ]
}
```

**Comment by johnnymagic** [comment]
After some digging, the applicant count is zero as no one "applied" but there is a candidate, meaning the client made them a candidate.  I'm not sure why we have a newApplicants property.  I changed this property to be candidateCount.  

Now we have an applicantCount (HPs who applied directly) and a candidateCount, which contains candidates who applied directly and candidates created by the client.

I won't close this one as I'd like you to confirm that works for the front end.  Let me know if it is OK.  Thanks.

**Comment by johnnymagic** [comment]
![image](https://cloud.githubusercontent.com/assets/2058501/21066902/04e1bdca-be1d-11e6-8e1f-c1092edabecd.png)

**Comment by badluck13** [comment]
About newApplicants property we have in the design a feature to say HA if there are new applicants from the last time they visited the job. We can figure if we want to take this or not, for now its not needed.

Yeah candidateCount is solving this issue, thank you @johnnymagic
