### ISSUE TITLE
Wrong path for Delete questions

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#2]
There is an error in path for this API endpoint:

DELETE /api/v1/clients/{jobId}/scl/{skillsChecklistId}/questions

It should be:

DELETE /api/v1/clients/**{clientId}/jobs/**{jobId}/scl/{skillsChecklistId}/questions

**Comment by johnnymagic** [comment]
This is resolved.

File Change: Controllers/ClientController.cs
