### ISSUE TITLE
API: HA missing JOB routes

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#21]
On HA we currently have just a piece of JOB routes compared to Admin ones

Here are HA JOB routes:
```
GET | POST /api/v1/ha/{clientId}/jobs
GET | POST | DELETE /api/v1/ha/{clientId}/jobs/{jobId}
GET /api/v1/ha/{clientId}/jobs/{jobId}/candidates
GET | POST /api/v1/ha/{clientId}/jobs/{jobId}/candidates/{candidateId}
GET | POST /api/v1/ha/{clientId}/jobs/{jobId}/scl/{sclId}
```
And here are Admin JOB routes:
```
GET | POST /api/v1/jobs
GET | POST | DELETE /api/v1/jobs/{jobId}
GET | POST | DELETE /api/v1/jobs/{jobId}/specialties
GET | POST | DELETE /api/v1/jobs/{jobId}/specialties/{specialtyId}
GET | DELETE /api/v1/jobs/{jobId}/shifts
POST | DELETE /api/v1/jobs/{jobId}/shifts/{shiftId}
GET | POST /api/v1/jobs/{jobId}/scl
GET | POST | DELETE /api/v1/jobs/{jobId}/scl/{sclId}
GET | POST | DELETE /api/v1/jobs/{jobId}/scl/{sclId}/questions
GET | DELETE /api/v1/jobs/{jobId}/scl/{sclId}/questions/{questionId}
```

We need to match all of this routes in to be able to use it fully. For now most important are

`GET | POST /api/v1/ha/{clientId}/jobs/{jobId}/specialties` to GET and ADD specialties to the job
`DELETE /api/v1/{clientId}/jobs/{jobId}/specialties/{specialtyId}` to delete specific specialty from the job
`GET | POST /api/v1/{clientId}/jobs/{jobId}/scl` to GET and ADD SCL's to job
`DELETE /api/v1/{clientId}/jobs/{jobId}/scl/{sclId}` and to remove SCL from the job

There is also a faster solution to add role 3 to this /api/v1/jobs/* calls we need

**Comment by badluck13** [comment]
Added role 3 to all needed routes, @johnnymagic please deploy them to the server, thank you!

**Comment by johnnymagic** [comment]
deployed
