### ISSUE TITLE
API: Change routes for HA scl answers

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#22]
We have this routes currently:

`GET /api/v1/scl/{sclId}/questions/{userId}/answers` - this one is used in all roles (this one can stay here but only for roles from 1 to 5)
`POST /api/v1/scl/{sclId}/answers`

Change them to use same route for HP role, and as they are connected to HP lets make them part of profile branch:

```
GET /api/v1/profile/scl/{sclId}/answers
POST /api/v1/profile/scl/{sclId}/answers
```

Also we should then map other routes that are here to their rightful places:

```
GET | POST /api/v1/profile/scl/
GET | POST | DELETE /api/v1/profile/scl/{sclId}
```

**Bonus point is if we merge `/api/v1/profile/scl/{sclId}/answers` to `/api/v1/profile/scl/{sclId}` as we can get and update questions/answers and delete SCL if needed all in same route.**

**Comment by johnnymagic** [comment]
Routes are now user-specific to the HP and available as:

POST /api/v1/profile/scl/{sclId}
GET /api/v1/profile/scl/{sclId}
