### ISSUE TITLE
API: Question answer update do not handle null values

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#23]
Submitting answers with null value return error: "answers[0].AnswerValue":["The Answer field is required."],

Also some question types can't have answer value like Titles for example.

STR:

Get HP token, then

`POST {{url}}/api/v1/scl/4625d3db-a048-425a-b322-4b055517bff3/answers`
with body:
```
[
  {
    "skillsChecklistQuestionId": "2cdd68e0-bcb8-414e-a608-42ddeca02d44",
    "questionTypeID": 1,
    "questionText": "Do you feel comfortable with a patient in distress?",
    "position": 1,
    "required": false,
    "answerValue": "1"
  },
  {
    "skillsChecklistQuestionId": "a2c3487e-ad7c-4712-b1ab-ca11caae7a2e",
    "questionTypeID": 1,
    "questionText": "Do you feel comfortable with yourself?",
    "position": 3,
    "required": false,
    "answerValue": null
  }
]
```

**Comment by badluck13** [comment]
Fixed this by sending only answered questions to the API, we may discuss if this is needed at all. cc @johnnymagic

**Comment by johnnymagic** [comment]
Yes, only answered is good. I'd rather treat zero as null for db
performance. I'm flexible though if you need it.

**Comment by badluck13** [comment]
Yeah this will work, lets close this one.
