### ISSUE TITLE
API: Get Job Scl questions with rank as HP role

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#24]
Create api endpoint for getting ranked questions with HP role, like in this route: 

`GET /api/v1/ha/{clientId}/jobs/{jobId}/scl/{sclId}`

but here with role 6 - HP

`GET /api/v1/myjobs/{jobId}/scl/{sclId}`

**Comment by johnnymagic** [comment]
deployed
