### ISSUE TITLE
API: Question update sets non present elements to null

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#25]
Use case, when updating SCL questions, for rank or answer value, we should send only the changes to the API to have a faster response, if we request 2 changed questions it would be much faster than 100, this is use case I'm working on DoddleNow/DoddleNow-FrontEnd#128

But if we send only the changed questions, all others will set their property we want to change to **null or 0**

In case of `POST /api/v1/scl/{sclId}/answers`, answerValue on other question is set to null 
and in case of `POST /api/v1/ha/{clientId}/jobs/{jobId}/scl/{sclId}` rank property will be set to 0

Steps to reproduce is simple:
- use `POST /api/v1/scl/4625d3db-a048-425a-b322-4b055517bff3/answers` with 3 answers, 
```
[
  {
    "skillsChecklistQuestionId": "0668bb82-71cb-4c57-98c5-bf04acc21695",
    "answerValue": "2"
  },
  {
    "skillsChecklistQuestionId": "0de9205a-e63f-4db7-84da-02f173c3d721",
    "answerValue": "3"
  },
  {
    "skillsChecklistQuestionId": "79c85f6a-8837-48f5-b3fd-6ebc9aee151c",
    "answerValue": "4"
  }
]
```
- confirm the resulted change on `/api/v1/scl/4625d3db-a048-425a-b322-4b055517bff3/questions/d0fbb274-f20d-4611-a7a0-6a7ea99dfa2b/answers` 
- then POST only one question and confirm that other are broth to null
```
[
  {
    "skillsChecklistQuestionId": "0668bb82-71cb-4c57-98c5-bf04acc21695",
    "answerValue": "1"
  }
]
```
This happens on the rank call the same but values are set to default 0 instead of null

**Comment by johnnymagic** [comment]
This is resolved.   I'm able to get a full list of questions/answers using above checklist and then update one question with the following:

```
[
  {
    "skillsChecklistQuestionId": "0668bb82-71cb-4c57-98c5-bf04acc21695",
    "questionTypeID": 2,
    "questionText": "Level I Trauma Center",
    "position": 7,
    "required": false,
    "answerValue": "3"
  }
]
```
