### ISSUE TITLE
API HP Profile SCL routes

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#26]
Add this routes to HP profile

GET /api/v1/profile/scl - returns list of scl connected to account
POST /api/v1/profile/scl - connect scl to profile - payload is scl object we want to add, or just an id and name of scl

**Comment by johnnymagic** [comment]
PostMan updated

GET /api/v1/profile/scl - returns list of scl connected to account

POST /api/v1/profile/scl - connects scl to profile - Payload is SCL object but you only need the ID to be successful

DELETE /api/v1/profile/scl - removes scl connection from profile.  Payload is SCL object but you only need the ID to be successful

**Comment by badluck13** [comment]
@johnnymagic please update DELETE to

DELETE /api/v1/profile/scl/:id

As most browser standards removes all body elements from DELETE post, so I cant work around it tonight.
