### ISSUE TITLE
POST to {{url}}/api/v1/profile/languages returns error

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#28]
Posting new language to {{url}}/api/v1/profile/languages is returning error :

```
"message": "An error has occurred.",
  "exceptionMessage": "Cannot insert the value NULL into column 'ID', table 'doddlenow.dbo.USER_LANGUAGE'; column does not allow nulls. INSERT fails.\r\nThe statement has been terminated.",
  "exceptionType": "System.Data.SqlClient.SqlException",
```

STR:
- Get HP token
- Execute Add Language postman call

**Comment by johnnymagic** [comment]
New database issue.  It did not retain the auto identity insert.  This would have occurred with new education, work history, certs, and others.  I've resolved on all.
