### ISSUE TITLE
API Parameter Naming

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#3]
I spent some time into testing and debugging API code, and I wanted to suggest a naming strategy for parameters. 
# Lets start with Model parameter for POST:

You use **clientModel** or **jobModel**. It would me much better to not use Model in the name of parameter, it has much more sense to be plain name of that model.

POST **carModel** {name: Tesla}

POST **car** {name: Tesla}
# Now lets go trough path parameter naming:

Use short names or abbreviation when possible, for example: 

POST /api/v1/jobs/{jobId}/scl/**{skillsChecklistId}**/questions/**{skillsChecklistQuestionId}**

It would me much cleaner if it looked like this:

POST /api/v1/jobs/{jobId}/scl/**{sclId}**/questions/**{questionId}**

Also there is use of both abbreviation scl and full name skillsChecklist in same url, this should be consistent, so it will be easier to maintain later on. 
## Last is naming the parameter by children, example:

POST /api/v1/clients/**{parentId}**/clients

parentId is a bit confusing, API hierarchy is read from left to right, so this parentId can be misread as parentId property of first client, and not that that should be a parent for second client. So it's much better to use clientId instead.

POST /api/v1/clients/**{clientId}**/clients

**Comment by johnnymagic** [comment]
For these Skills Checklist parameter names is this what you would like?

skillsChecklistId  =  sclId
questionId = questionId
skillsChecklistQuestionId == sclQuestionId
answerId == answerId

It is important to note that a skillsChecklistQuestionId is a unique identifier pairing the skillsChecklistId and the questionId.   Questions can be re-used between checklist versions and checklists themselves.  The skillsChecklistQuestionId is the only unique identifier for a question.  It can be used individually to find a question across any checklist version. 

I never like shortening names unless there is a definitive acronym and it is capitalized.  If we have skillsChecklistCategoryId, would it be sclCatId?  Others will be

skillsChecklistTypeId == sclTypeId
skillsChecklistSignatureId = sclSignatureId

Is all of that good with you?  If so, I'll change them.

**Comment by johnnymagic** [comment]
All of the items besides the parameter names have been resolved.

For the models, adjusted client, job, specialty, skillsChecklist, question, and user.

File Changes thus far:
Controllers : ClientController, JobController, SkillsChecklistController, SpecialtyController, UserController

Models: ClientModel, JobModel, QuestionModel, SkillsChecklistModel, SpecialtyModel, UserModel

**Comment by johnnymagic** [comment]
Updated parameter names:
skillsChecklist == scl
skillsChecklistId == sclId
skillsChecklistQuestionId == questionId

The SkillsChecklistQuestionID was exposing more about the data model than necessary.  The UI should never know the difference between questionId and skillsChecklistQuestionId.  All endpoints were simplified by just questionId.

File Changes: 
JobController.cs
ClientController.cs
SkillsChecklistController.cs

Commit b5198638
