### ISSUE TITLE
API: Flag assessments when they are finished

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#31]
Add a flag for finished assessments on this call:

GET /api/v1/assessments/user/{userId}

**Comment by johnnymagic** [comment]
You will now see a questionCount, answerCount, and a complete flag returned. 

![image](https://user-images.githubusercontent.com/2058501/27875277-7bf5f960-6167-11e7-89c8-eac8a1a80462.png)
