### ISSUE TITLE
API: Only return unanswered questions on Assessment call

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#32]
Only return unanswered questions on get Assessment questions call:

`GET /api/v1/assessments/{sclId}/questions`

**Comment by johnnymagic** [comment]
This is now an HP only API call.  It will only return unanswered questions.  For non-HP calls, use 
GET /api/v1/scl/{sclId}/questions.  The POSTMan collection has been updated and these are under the Assessments section.

GET /api/v1/assessments/{sclId}/questions
