### ISSUE TITLE
Delete question from Scl

### ISSUE THREAD

**Issue by iborismb** [DoddleNow/DoddleNow-BackEnd#5]
# Delete question from Job Scls

Example

**Request URL**:http://doddlenowapi-test.us-west-2.elasticbeanstalk.com/api/v1/jobs/f2e9db51-68cf-4ec7-afa3-75d783757c2e/scl/44caf2dd-b8e2-486b-bc14-29aadb8c5df4
**Request Method**:DELETE
**Status Code**:500 Internal Server Error

**Comment by johnnymagic** [comment]
This is resolved.

File Change:  usp_DeleteSkillsChecklist.sql
