### ISSUE TITLE
POST /myjobs/:id unable to update applied property

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#8]
Posting applied status is not changing that property

Steps to reproduce:

- go to Post man
- get HP token
- Get HP's Job by ID, see that applied property is false
- go to Update HP Job by ID, and add this as raw
```
{
  "applied": "true"
}
```
- go back to HP's Job by ID, see that applied property is still false

**Comment by johnnymagic** [comment]
This is resolved.

Values can be sent in together or only one.
1.
{
	"starred":true,
	"applied":false
}

2.
{
	"applied": true
}

The second will not wipe out the starred value

File Changes: MyJobsController.cs; HPJobModel.cs;  usp_UpdateUserJob.sql

**Comment by johnnymagic** [comment]
PostMan updated

**Comment by badluck13** [comment]
Works great, this is already on the server, so you can star and apply for jobs as HP role.
