### ISSUE TITLE
GET /myjobs total status update

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#9]
Finished integrating this api and then figured out we configured it wrong.
this fields: 
```
"totalStarred": 66,
"totalInterested": 66,
"totalApplied": 0
"totalMatches": 300 -- new - we used totalCount but that is unusable in this situation
```
Should be global, so they do not change if we narrow down the results. Current behavior will change this numbers when we filter results. For example I want to filter all Starred and I end up with starred saying the same, but others are going down, because this call counts number of Applied in this results. And we need total number for all results not narrowed down.

**Comment by johnnymagic** [comment]
Good catch. Yes, that could cause havoc.  

totalCount and totalPages are now reflective of the results given

totalStarred, totalInterested, and totalApplied are global (will not change based on results)

**Comment by badluck13** [comment]
Great! Please add "totalMatches": xxxx for total number of jobs returned to dashboard, it's same number as totalCount without any filters. But it's global so I can use it on layout for Total Matched filter.

**Comment by johnnymagic** [comment]
Check it out.  I think I did what you're asking.  This is live.

**Comment by badluck13** [comment]
@johnnymagic yes it's perfect thanks.
